accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

manages_tour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('sales.urls')),
    path('sales/', include('sales.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home, name='home'),
    
    # Menu
    path('menu', views.menu, name='menu'),

    # Sales
    path('sales/', views.sale_list, name='sale_list'),
    path('sales/create/', views.create_sale, name='sale_create'),
    path('sales/<int:sale_id>/', views.sale_detail_view, name='sale_detail'),
    path('sales/sale_tour/<int:tour_id>/create', views.create_sale_tour, name='create_sale_tour'),
    # path('sales/<int:pk>/edit/', views.sale_update, name='sale_update'),
    # path('sales/<int:pk>/delete/', views.sale_delete, name='sale_delete'),


    # Agencies
    path('agencies/', views.agency_list, name='agency_list'),
    path('agencies/create/', views.agency_create, name='agency_create'),
    path('agencies/<int:pk>/edit/', views.agency_update, name='agency_update'),
    path('agencies/<int:pk>/delete/', views.agency_delete, name='agency_delete'),

    # Tours
    path('tours/', views.tour_list, name='tour_list'),
    path('tours/tour/<int:id>', views.tour, name='tour'),
    path('tours/create/', views.tour_create, name='tour_create'),
    path('tours/<int:pk>/edit/', views.tour_update, name='tour_update'),
    path('tours/<int:pk>/delete/', views.tour_delete, name='tour_delete'),

    # TourImage
    path('tourImage/create/<int:pk>', views.tour_image_create, name='tour_image_create'),
    path('tourImage/<int:pk>/delete', views.tour_image_delete, name='tour_image_delete'),

    # Clients
    path('clients/', views.client_list, name='client_list'),
    path('clients/create/', views.client_create, name='client_create'),
    path('clients/<int:pk>/edit/', views.client_update, name='client_update'),
    path('clients/<int:pk>/delete/', views.client_delete, name='client_delete'),

    # Payments
    path('payments/create/', views.client_create, name='payment_create'),
    
    # Referrers
    path('referrers/create/', views.referrer_create, name='referrer_create'),
]

sales/models.py
from django.db import models
from django.contrib.auth.models import User
from cities_light.models import Country, City
from uuid import uuid4
import os


def tour_main_image_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"main_{uuid4().hex}.{ext}"
    return os.path.join('tours', str(instance.id), filename)

def tour_image_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid4().hex}.{ext}"
    tour_id = instance.tour.id if instance.tour else 'unknown'
    return os.path.join('tours', str(tour_id), 'gallery', filename)

class Agency(models.Model):
    nit = models.CharField(max_length=10)
    name_agency = models.CharField(max_length=100)
    email_agency = models.EmailField(max_length=100)
    tel_agency = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"{self.nit}-{self.name_agency}"

class Referrer(models.Model):
    type_doc = models.CharField(max_length=10)
    num_doc = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=200)
    tel = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    client_data = models.CharField(max_length=200)
    bank = models.CharField(max_length=100)
    type_count = models.CharField(max_length=100)
    num_count = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"{self.num_doc}-{self.name}"

class Provider(models.Model):
    nit = models.CharField(max_length=10)
    name_provider = models.CharField(max_length=100)
    email_provider = models.EmailField(max_length=100)
    tel_provider = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"{self.nit}-{self.name_provider}"

class Tour(models.Model):
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE, related_name='tours')
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, related_name='tours')
    name_tour = models.CharField(max_length=100)
    date_tour = models.DateTimeField(null=True, blank=True, verbose_name="Fecha del Tour")
    description = models.TextField(max_length=500)
    price_sale = models.FloatField()
    price_total = models.FloatField()
    image_path = models.ImageField(upload_to=tour_main_image_upload_path, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def save(self, *args, **kwargs):
        try:
            # Verifica si ya existe una imagen previa
            old = Tour.objects.get(pk=self.pk)
            if old.image_path and old.image_path!= self.image_path:
                if os.path.isfile(old.image_path.path):
                    os.remove(old.image_path.path)
        except Tour.DoesNotExist:
            pass  # No hay imagen previa

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Eliminar la imagen principal si existe
        if self.image_path:
            self.image_path.delete(save=False)  # Elimina también del almacenamiento

        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name_tour

class TourImage(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, related_name='images')
    image_path = models.ImageField(upload_to=tour_image_upload_path)
    caption = models.CharField(max_length=50, blank=True, null=True)

    def delete(self, *args, **kwargs):
        # Borrar el archivo físico primero
        if self.image_path and os.path.isfile(self.image_path.path):
            os.remove(self.image_path.path)
        super().delete(*args, **kwargs)

    def __str__(self):
        return f"Imagen de {self.tour.name_tour}"

class Client(models.Model):
    TYPE_DOC_CHOICES = [
        ('CC', 'Cédula de ciudadanía'),
        ('CE', 'Cédula de extranjería'),
        ('TI', 'Tarjeta de identidad'),
        ('PP', 'Pasaporte'),
        ('NIT', 'NIT'),
    ]
    type_doc = models.CharField(max_length=10, choices=TYPE_DOC_CHOICES)
    num_doc = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    tel = models.CharField(max_length=200, blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    hotel = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"{self.num_doc}-{self.name}"

class Role(models.Model):
    role = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"{self.role}"

class Employee(models.Model):
    TYPE_DOC_CHOICES = [
        ('CC', 'Cédula de ciudadanía'),
        ('CE', 'Cédula de extranjería'),
        ('TI', 'Tarjeta de identidad'),
        ('PP', 'Pasaporte'),
        ('NIT', 'NIT'),
    ]

    type_doc = models.CharField(max_length=10, choices=TYPE_DOC_CHOICES)
    num_doc = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    tel = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    agency = models.ForeignKey(Agency, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    rol = models.ForeignKey(Role, on_delete=models.SET_NULL,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"{self.num_doc}-{self.name}"

class Sale(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, related_name='sales')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='sales')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='sales')
    referrer = models.ForeignKey(Referrer,on_delete=models.SET_NULL, blank=True, null=True, related_name='sales')
    value_sale_unit = models.FloatField()
    quantity = models.IntegerField()
    total_sale = models.FloatField()
    observations = models.CharField(max_length=250, default='')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"Sale {self.id}: Tour {self.tour_id}, Client {self.client_id}"
    
class Payment(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name='payments')
    options_payment = models.CharField(max_length=100)
    bank_platform = models.CharField(max_length=100, blank=True)
    value = models.FloatField()
    payment_date = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    payment_reference = models.CharField(max_length=100, blank=True)
    confirmed = models.BooleanField(default=True)
    note = models.TextField(blank=True)
    document_url = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    def __str__(self):
        return f"Payment {self.value}-Sale {self.sale.id}"

class Commission(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name='commissions')
    type = models.CharField(max_length=100)
    beneficiary_num = models.CharField(max_length=100)
    beneficiary_name = models.CharField(max_length=100)
    percentage = models.FloatField()
    value_sale = models.FloatField()
    value_commission = models.FloatField()
    observations = models.CharField(max_length=250, default='')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

sales/forms.py
from django import forms
from .models import (
    Agency, Provider, Referrer, Tour, TourImage,
    Client, Employee, Sale, Payment, Commission
)


class AgencyForm(forms.ModelForm):
    class Meta:
        model = Agency
        fields = ['nit', 'name_agency', 'email_agency', 'tel_agency', 'contact']


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ['nit', 'name_provider', 'email_provider', 'tel_provider', 'contact']


class ReferrerForm(forms.ModelForm):
    class Meta:
        model = Referrer
        fields = [
            'type_doc', 'num_doc', 'name', 'tel', 'email',
            'client_data', 'bank', 'type_count', 'num_count'
        ]


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = [
            'agency', 'provider', 'name_tour', 'description',
            'price_sale', 'price_total', 'image_path'
        ]


class TourImageForm(forms.ModelForm):
    class Meta:
        model = TourImage
        fields = [
            'image_path', 'caption'
        ]

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['type_doc', 'num_doc', 'name', 'email', 'tel', 'hotel']


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['type_doc', 'num_doc', 'name', 'tel', 'email']


# class SaleForm(forms.ModelForm):
#     class Meta:
#         model = Sale
#         fields = [
#             'tour', 'client', 'vendor', 'referrer',
#             'value_sale_unit', 'quantity', 'total_sale', 'observations'
#         ]

# forms.py
class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = [
            'tour',
            'client',
            'employee',
            'referrer',
            'value_sale_unit',
            'quantity',
            'observations',
        ]
        widgets = {
            'tour': forms.Select(attrs={'class': 'form-control'}),
            'client': forms.Select(attrs={'class': 'form-control'}),
            'employee': forms.Select(attrs={'class': 'form-control'}),
            'referrer': forms.Select(attrs={'class': 'form-control'}),
            'value_sale_unit': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'observations': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Observaciones adicionales (opcional)'
            }),
        }
        labels = {
            'tour': 'Tour',
            'client': 'Cliente',
            'employee': 'Employee',
            'referrer': 'Referido por',
            'value_sale_unit': 'Valor unitario de la venta',
            'quantity': 'Cantidad',
            'observations': 'Observaciones',
        }


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['sale', 'options_payment', 'value']


class CommissionForm(forms.ModelForm):
    class Meta:
        model = Commission
        fields = [
            'sale', 'type', 'beneficiary_num', 'beneficiary_name',
            'percentage', 'value_sale', 'value_commission', 'observations'
        ]

sales/templates/includes/carousel-main.html
<div class="carousel-container">
    <div class="carousel-track">
    {% for tour in tours %}
      {% for image in tour.images.all %}
        <img src="{{ image.image_path }}" alt="{{ image.caption|default:'Imagen del tour' }}" class="carousel-image">
        {% if image.caption %}
            <p class="caption">{{ image.caption }}</p>
        {% endif %}
      {% endfor %}
    {% endfor %}
    </div>
    <button class="carousel-button prev">&#10094;</button>
    <button class="carousel-button next">&#10095;</button>
</div>

sales/templates/includes/carousel.html
<div class="carousel-container">
    <div class="carousel-track">
      {% for image in tour.images.all %}
        <img src="{{ image.image_path }}" alt="{{ image.caption|default:'Imagen del tour' }}" class="carousel-image">
        {% if image.caption %}
            <p class="caption">{{ image.caption }}</p>
        {% endif %}
      {% endfor %}
    </div>
    <button class="carousel-button prev">&#10094;</button>
    <button class="carousel-button next">&#10095;</button>
</div>

sales/templates/includes/footer.html
<footer class="footer">
    Copyright 2020. Todos los derechos reservados
</footer>

sales/templates/includes/form_client.html
<form method="post" class="form_client" id="formCreateClient" data-url="{% url 'client_create' %}">
    {% csrf_token %}

    <div class="form_client__field">
        <label for="tipo_doc">Tipo de Documento</label>
        <select name="type_doc" id="type_doc" name="type_doc" required>
            <option value="">-- Seleccione --</option>
            <option value="CC">CC</option>
            <option value="TI">TI</option>
            <option value="PP">PP</option>
            <option value="CE">CE</option>
            <option value="NIT">NIT</option>
        </select>
    </div>

    <div class="form_client__field">
        <label for="num_doc">Número de Documento</label>
        <input type="text" name="num_doc" id="num_doc" required>
    </div>

    <div class="form_client__field">
        <label for="name">Nombre</label>
        <input type="text" name="name" id="name" required>
    </div>

    <div class="form_client__field">
        <label for="email">Correo Electrónico</label>
        <input type="email" name="email" id="email" required>
    </div>

    <div class="form_client__field">
        <label for="tel">Teléfono</label>
        <input type="text" name="tel" id="tel">
    </div>

    <div class="form_client__field">
        <label for="hotel">Hotel</label>
        <input type="text" name="hotel" id="hotel" required>
    </div>

    <button type="submit" class="btn">Guardar Cliente</button>
</form>

sales/templates/includes/form_payment.html
<form method="post" class="form_payment" id="formCreatePayment" data-url="{% url 'payment_create' %}">
    {% csrf_token %}

    <!-- Venta asociada -->
    <!-- <div class="form_sale__field">
        <label for="sale">Venta</label>
        <select id="sale" name="sale" required>
            <option value="{{sale.id}}" selected>{{sale.id}}</option>
            {% for sale in sales %}
                <option value="{{ sale.id }}">#{{ sale.id }} - {{ sale.tour.name }}</option>
            {% endfor %}
        </select>
    </div> -->

    <!-- Método de pago -->
    <div class="form_sale__field">
        <label for="payment_method">Método de pago</label>
        <select id="payment_method" name="options_payment" required>
            <option value="">-- Seleccione un método --</option>
            <option value="Efectivo">Efectivo</option>
            <option value="Transferencia">Transferencia</option>
            <option value="TarjetaCredito">Tarjeta de Crédito</option>
            <option value="TarjetaDebito">Tarjeta de Débito</option>
        </select>
    </div>

    <!-- Banco/Plataforma -->
    <div class="form_sale__field" id="bankPlatformField">
    <label for="payment_bank">Banco/Plataforma</label>
    <select id="payment_bank" name="options_bank" required>
        <option value="">-- Seleccione --</option>
        <option value="Nequi">Nequi</option>
        <option value="Daviplata">Daviplata</option>
        <option value="Bancolombia">Bancolombia</option>
        <option value="BBVA">BBVA</option>
        <option value="Davivienda">Davivienda</option>
    </select>
    </div>


    <!-- Valor del abono -->
    <div class="form_sale__field">
        <label for="payment_value">Valor del abono</label>
        <input type="number" id="payment_value" name="value" placeholder="Ingrese el valor abonado" required />
    </div>

    <!-- Fecha de pago -->
    <!-- <div class="form_sale__field">
        <label for="payment_date">Fecha de pago</label>
        <input type="datetime-local" id="payment_date" name="payment_date" />
    </div> -->

    <!-- Referencia -->
    <div class="form_sale__field">
        <label for="payment_reference">Referencia</label>
        <input type="text" id="payment_reference" name="payment_reference" placeholder="Referencia del pago" />
    </div>

    <!-- Confirmado -->
    <!-- <div class="form_sale__field">
        <label for="confirmed">¿Confirmado?</label>
        <select id="confirmed" name="confirmed">
            <option value="false">No</option>
            <option value="true" selected>Sí</option>
        </select>
    </div> -->

    <!-- Nota -->
    <div class="form_sale__field">
        <label for="note">Nota</label>
        <textarea id="note" name="note" rows="3" placeholder="Ingrese una nota adicional"></textarea>
    </div>

    <!-- URL documento -->
    <!-- <div class="form_sale__field">
        <label for="document_url">URL del documento</label>
        <input type="url" id="document_url" name="document_url" placeholder="https://..." />
    </div> -->

    <!-- Botón registrar -->
    <button type="submit" class="btn btn-success">Registrar Abono</button>
</form>

sales/templates/includes/form_referrer.html
<form method="post" class="form_referrer" id="formCreateReferrer" data-url="{% url 'referrer_create' %}">
    {% csrf_token %}

    <div class="form_referrer__field">
        <label for="type_doc">Tipo de Documento</label>
        <select name="type_doc" id="type_doc" required>
            <option value="">-- Seleccione --</option>
            <option value="CC">CC</option>
            <option value="TI">TI</option>
            <option value="PP">PP</option>
            <option value="CE">CE</option>
            <option value="NIT">NIT</option>
        </select>
    </div>

    <div class="form_referrer__field">
        <label for="num_doc">Número de Documento</label>
        <input type="text" name="num_doc" id="num_doc" required>
    </div>

    <div class="form_referrer__field">
        <label for="name">Nombre</label>
        <input type="text" name="name" id="name" required>
    </div>

    <div class="form_referrer__field">
        <label for="tel">Teléfono</label>
        <input type="text" name="tel" id="tel" required>
    </div>

    <div class="form_referrer__field">
        <label for="email">Correo Electrónico</label>
        <input type="email" name="email" id="email" required>
    </div>

    <div class="form_referrer__field">
        <label for="client_data">Cliente Referido</label>
        <input type="text" name="client_data" id="client_data" required>
    </div>

    <div class="form_referrer__field">
        <label for="bank">Banco</label>
        <input type="text" name="bank" id="bank" required>
    </div>

    <div class="form_referrer__field">
        <label for="type_count">Tipo de Cuenta</label>
        <select name="type_count" id="type_count" required>
            <option value="">-- Seleccione --</option>
            <option value="Ahorros">Ahorros</option>
            <option value="Corriente">Corriente</option>
            <option value="Nequi">Nequi</option>
            <option value="Daviplata">Daviplata</option>
        </select>
    </div>

    <div class="form_referrer__field">
        <label for="num_count">Número de Cuenta</label>
        <input type="text" name="num_count" id="num_count" required>
    </div>

    <button type="submit" class="btn">Guardar Referido</button>
</form>

sales/templates/includes/form_tour.html
<form id="formCreateTour" method="POST" action="{% url 'tour_create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="formCreateTour__field">
        <label for="agency_tour">Agencia</label>
        <select name="agency" id="agency_tour" required>
            <option value="">-- Seleccione --</option>
            {% for agency in agencies %}
            <option value="{{agency.id}}">{{agency}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="formCreateTour__field">
        <label for="provider_tour">Proveedor</label>
        <select name="provider" id="provider_tour" required>
            <option value="">-- Seleccione --</option>
            {% for provider in providers %}
            <option value="{{provider.id}}">{{provider}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="formCreateTour__field">
        <label for="name_tour">Nombre del tour</label>
        <input type="text" name="name_tour" id="name_tour" required>
    </div>
    <div class="formCreateTour__field">
        <label for="date_tour">Fecha del tour</label>
        <input type="datetime-local" name="date_tour" id="date_tour" required>
    </div>
    <div class="formCreateTour__field">
        <label for="price_proveedor">Precio de proveedor</label>
        <input type="number" name="price_total" id="price_proveedor" step="0.01" required>
    </div>
    <div class="formCreateTour__field">
        <label for="price_sale">Precio de venta</label>
        <input type="number" name="price_sale" id="price_sale" step="0.01" required>
    </div>
    <div class="formCreateTour__field">
        <label for="tour_description">Descripción</label>
        <textarea id="tour_description" name="description" rows="3" placeholder="Descripción del Tour"></textarea>
    </div>
    <div class="formCreateTour__field">
        <label for="image_path">Imagen del tour</label>
        <input type="file" name="image_path" id="image_path" accept="image/*">
    </div>
    
    <button type="submit" class="btn btn-success">Guardar</button>
    </div>
</form>

sales/templates/includes/form_tour_photos.html
<form id="formTourPhotos"  method="POST" action="{% url 'tour_image_create' tour.id %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="formTourPhotos__field">
        <label for="id_tour">Tour</label>
        <select name="tour" id="id_tour" readonly>
            <option value="{{tour.id}}" selected>{{tour.name_tour}}</option>
        </select>
    </div>

    <div class="formTourPhotos__field">
        <label for="image_path">Imagen del tour</label>
        <input type="file" name="image_path" id="image_path" accept="image/*">
    </div>

    <div class="formTourPhotos__field">
        <label for="name_image_tour">Nombre imagen</label>
        <input type="text" name="caption" id="name_image_tour">
    </div>
    <!-- Botón Guardar -->
    <button type="submit" class="btn btn-success">Guardar</button>
</form>

sales/templates/includes/header.html
<header class="container-header surface">
    <div class="header">
        <div class="logo">
            <h1><a href="/">TourManager</a></h1>
        </div>

        <!-- Botón hamburguesa -->
        <button class="menu-toggle" id="menu-toggle">&#9776;</button>

        <nav class="navbar" id="navbar">
            <ul class="nav-links">
                <li><a href="/">Inicio</a></li>
                <li><a href="#">Referidos</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'menu' %}">Menu</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Cerrar sesión</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

sales/templates/includes/list_tour.html
<section class="tours-section">
    <h2 class="section-title">Nuestros Tours</h2>
    <div class="tours-grid">

        {% for tour in tours %}
            <div class="tour-card">
                <img src="{{tour.image_path.url}}" alt="Tour al Caribe" class="tour-img">
                <div class="tour-info">
                    <h3 class="tour-title">{{tour.name_tour}}</h3>
                    <p class="tour-date">{{tour.date_tour}}</p>
                    <p class="tour-desc">{{tour.description}}</p>
                    {% if view_sale_list %}
                    <a href="#" class="btn-tour" id="select_tour" onclick='select_tour("{{tour.name_tour}}", "{{tour.price_sale}}")'>Seleccionar</a>
                    {% endif %}
                    {% if view_home %}
                    <a href="{% url 'tour' tour.id %}" class="btn-tour" id="select_tour">Ver más...</a>
                    {% endif %}

                    <!-- <a href="#" class="btn-tour" id="select_tour">Ver más</a> -->
                </div>
            </div>
        {% endfor %}

    </div>
</section>

sales/templates/includes/table_payments.html
<div id="paymentsContainer" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">
  <!-- Aquí se agregarán las tarjetas -->
</div>